// <auto-generated />
using Langua.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Langua.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250530145226_PLA1A2TextMigration")]
    partial class PLA1A2TextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Langua.Models.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Texts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "Swedish",
                            LanguageText = "Jag heter Emma och jag är tretton år. Jag bor i ett litet hus med min mamma, min pappa och vårt husdjur. Vi har en hund som heter Max. Han är tre år gammal och väldigt snäll.\r\n\r\nVarje morgon går jag ut med Max innan jag går till skolan. Han gillar att springa och leka i parken. När jag kommer hem från skolan, väntar han alltid vid dörren. Då brukar vi leka lite till eller gå en promenad tillsammans.\r\n\r\nMin mamma tycker också mycket om Max. Hon köper ofta leksaker och godis till honom. Min pappa gillar att träna honom. Max kan sitta, ligga och ge tass. Han är väldigt smart!\r\n\r\nPå helgerna åker vi ibland till landet. Max älskar att vara där, för han kan springa fritt. Han jagar fjärilar och nosar på allt.\r\n\r\nJag älskar min hund och kan inte tänka mig ett liv utan honom.",
                            Level = "A1",
                            TextTitle = "Mitt husdjur"
                        },
                        new
                        {
                            Id = 2,
                            Language = "Swedish",
                            LanguageText = "Det är lördag och vädret är fint. Solen skiner och det är varmt i luften. Många människor är ute. Några sitter på bänkar och läser böcker. Andra går promenader eller leker med sina barn.\r\n\r\nEn liten pojke cyklar runt med sin pappa. De stannar vid en glasskiosk och köper varsin glass. Pappan tar choklad och pojken väljer jordgubb. De sätter sig i gräset och äter i solen. Fåglarna kvittrar i träden och det luktar blommor överallt.\r\n\r\nLite längre bort spelar några ungdomar fotboll. De skrattar och springer mycket. En hund springer efter bollen och alla tycker det är roligt. En flicka gör mål och alla klappar händerna.\r\n\r\nEn gammal man matar duvor vid fontänen. Han har med sig en liten påse med bröd. Duvorna flyger runt honom och pickar på marken.\r\n\r\nPå eftermiddagen börjar det blåsa lite, men solen är fortfarande framme. Några människor går hem, men många stannar kvar. Det är en härlig dag i parken och alla verkar glada.",
                            Level = "A1",
                            TextTitle = "En dag i parken"
                        },
                        new
                        {
                            Id = 3,
                            Language = "Swedish",
                            LanguageText = "Jag heter Lucas och jag går i en skola som heter Solskolan. Den ligger tio minuter från mitt hus. Jag brukar cykla dit varje morgon. Skolan är ganska stor och har många klassrum, en matsal och en gympasal.\r\n\r\nMitt klassrum ligger på andra våningen. Det finns stora fönster så rummet är ljust. I klassrummet har vi bänkar, stolar, en whiteboard och en stor klocka på väggen. Längst bak i rummet finns en bokhylla med böcker som vi får läsa på rasterna.\r\n\r\nMin favoritplats är vid fönstret. Där sitter jag varje dag. Jag tycker om att titta ut när jag tänker. På väggarna i klassrummet hänger teckningar och affischer med svenska ord och bilder.\r\n\r\nVi har också ett grupprum bredvid klassrummet. Där jobbar vi ibland i små grupper. Det är tystare där, och det finns ett litet bord och några stolar.\r\n\r\nJag gillar min skola. Den är fin och jag trivs bra där.",
                            Level = "A1",
                            TextTitle = "Lucas berättar om sin skola"
                        },
                        new
                        {
                            Id = 4,
                            Language = "Swedish",
                            LanguageText = "Jag heter Elin och min bästa vän heter Anna. Vi träffades i skolan för tre år sedan och har varit vänner sedan dess. Anna är 17 år och bor nära mig, så vi ses nästan varje dag.\r\n\r\nAnna har långt blont hår och gröna ögon. Hon är ganska kort och skrattar mycket. Hon tycker om att rita och lyssna på musik. Ibland ritar hon porträtt av sina vänner, och hon har ritat ett jättefint porträtt av mig. Det hänger på väggen i mitt rum.\r\n\r\nVi tycker båda om att baka, så ofta gör vi muffins eller chokladkaka tillsammans på helgerna. Anna gillar också att läsa böcker, särskilt böcker om äventyr och mysterier. Jag brukar låna böcker av henne när jag inte har något att läsa.\r\n\r\nHon är snäll, rolig och alltid hjälpsam. När jag är ledsen, får hon mig att skratta. Jag är glad att jag har en vän som Anna. Jag hoppas att vi alltid kommer att vara vänner.",
                            Level = "A1",
                            TextTitle = "Min vän Anna"
                        },
                        new
                        {
                            Id = 5,
                            Language = "Swedish",
                            LanguageText = "Det är måndag morgon och Erik har bråttom till jobbet. Himlen är grå och det blåser lite, men han tänker inte så mycket på vädret. Han dricker snabbt sitt kaffe, tar på sig jackan och springer till bussen.\r\n\r\nNär han kommer fram till busshållplatsen börjar det regna. Först bara några droppar, men snart blir det ett riktigt ösregn. Erik letar i sin väska efter sitt paraply, men då kommer han på att han glömde det i hallen hemma.\r\n\r\nBussen är sen, och Erik blir blöt. När bussen äntligen kommer är hans byxor och skor redan genomvåta. På bussen sitter han tyst och tittar ut genom fönstret. Alla andra verkar ha tagit med sig paraply.\r\n\r\nNär han kommer till jobbet, skrattar hans kollega och säger:\r\n– Du borde nog kolla vädret innan du går hemifrån!\r\n\r\nErik ler och går direkt till toaletten för att torka sig lite. Nästa gång, tänker han, ska han inte glömma paraplyet.",
                            Level = "A2",
                            TextTitle = "Erik glömmer sitt paraply"
                        },
                        new
                        {
                            Id = 6,
                            Language = "Swedish",
                            LanguageText = "Vi är fyra personer i min familj: min mamma, min pappa, min storasyster och jag. Jag är 20 år gammal och bor fortfarande hemma medan jag studerar på universitetet. Min syster är 23 och jobbar som sjuksköterska på ett sjukhus i närheten.\r\n\r\nMin pappa är 52 år och arbetar som elektriker. Han tycker om att fixa saker i huset och är väldigt händig. Min mamma är 49 år och jobbar deltid på ett café. Hon älskar att baka och lagar alltid god mat till familjen.\r\n\r\nVarje söndag har vi en tradition. Vi äter middag tillsammans och spelar sällskapsspel efteråt. Ibland bjuder vi också in våra morföräldrar. Det är alltid trevligt, och vi skrattar mycket.\r\n\r\nVi har också en katt som heter Maja. Hon är vit med svarta fläckar och gillar att ligga i solen på balkongen. Hon är en viktig del av familjen.",
                            Level = "A2",
                            TextTitle = "Min familj och våra traditioner"
                        },
                        new
                        {
                            Id = 7,
                            Language = "Swedish",
                            LanguageText = "På söndagar behöver jag inte ställa någon väckarklocka. Jag brukar vakna vid nio och ligger kvar i sängen en stund innan jag går upp. Efter en lång dusch gör jag frukost – oftast yoghurt med bär och en kopp te.\r\n\r\nVid elva går jag ut på en promenad i parken. Jag gillar att lyssna på musik eller en podcast medan jag går. Ibland möter jag min vän Julia där, och då går vi tillsammans och pratar om veckan som har gått.\r\n\r\nEfter promenaden handlar jag mat. Jag planerar ofta veckans middagar redan på söndagen. Jag gillar att laga mat, så jag väljer gärna nya recept att prova.\r\n\r\nPå eftermiddagen brukar jag städa lägenheten och tvätta kläder. Det är inte så roligt, men det känns skönt när allt är rent och i ordning.\r\n\r\nPå kvällen lagar jag något gott och ser en film eller läser en bok. Jag försöker gå och lägga mig tidigt för att vara pigg till måndag morgon.",
                            Level = "A2",
                            TextTitle = "Linas söndag"
                        },
                        new
                        {
                            Id = 8,
                            Language = "Swedish",
                            LanguageText = "Jag bor i en liten lägenhet i stan. Jag har ett eget rum som är ganska litet, men det är mysigt och trivsamt. I mitt rum finns en enkelsäng, ett skrivbord, en stol och en bokhylla där jag har mina böcker och några foton.\r\n\r\nRummet har ett stort fönster som släpper in mycket ljus på dagen. Under fönstret står en liten soffa där jag ofta sitter och läser eller lyssnar på musik.\r\n\r\nJag har också några växter på fönsterbrädan. Min favoritväxt är en liten kaktus som är lätt att ta hand om.\r\n\r\nDet jag tycker bäst om med mitt rum är de gröna väggarna och att det är tyst där, så jag kan koncentrera mig när jag pluggar eller skriver. På kvällarna tänder jag en liten lampa som ger ett varmt och skönt ljus.",
                            Level = "A2",
                            TextTitle = "Mitt rum i lägenheten"
                        },
                        new
                        {
                            Id = 9,
                            Language = "Swedish",
                            LanguageText = "Hej!\r\n\r\nJag heter Erik och jag är 28 år. Jag bor i Göteborg tillsammans med min sambo. På fritiden gillar jag att spela fotboll, läsa böcker och resa.\r\n\r\nJag vill gärna söka jobbet som kundserviceassistent hos er. Jag tycker om att hjälpa människor och lösa problem. Jag är också van vid att arbeta i team och har goda kommunikationsfärdigheter. Mina styrkor är att jag är tålamodig, ansvarsfull och noggrann. Jag är van vid att använda olika datorprogram och lär mig snabbt nya system.\r\n\r\nTidigare har jag arbetat på ett callcenter där jag hjälpte kunder med deras frågor och beställningar. Det var ofta hektiskt, men jag lärde mig att hantera stress och hålla ett vänligt bemötande även i svåra situationer.\r\n\r\nJag tror att mina erfarenheter och min personlighet passar bra för tjänsten hos er. Jag ser fram emot möjligheten att träffa er för en intervju.\r\n\r\nTack för er tid!\r\n\r\nMed vänlig hälsning,\r\nErik",
                            Level = "B1",
                            TextTitle = "Erik skriver ett personligt brev"
                        },
                        new
                        {
                            Id = 10,
                            Language = "Swedish",
                            LanguageText = "I mitt sovrum finns en ganska stor garderob där jag förvarar alla mina kläder. Jag har många tröjor, särskilt hoodies, eftersom jag tycker det är bekvämt och varmt. Min favorithoodie är mörkblå och har en stor ficka fram där jag kan stoppa händerna.\r\n\r\nJag har också flera skjortor, både kortärmade och långärmade. De flesta är i neutrala färger som vit, grå och svart, men jag har några med mönster också. Mina favoritbyxor är ett par svarta jeans som jag använder nästan varje dag. Jag har också några chinos i olika färger, till exempel beige och mörkgrön.\r\n\r\nI garderoben hänger mina jackor och rockar. På vintern använder jag en tjock svart vinterjacka med luva, och på hösten har jag en lättare regnjacka. Jag brukar lägga mina mössor, vantar och halsdukar på en hylla högst upp.\r\n\r\nJag försöker alltid hålla ordning i min garderob, så att jag snabbt kan hitta det jag behöver. Det gör det enklare att välja kläder på morgonen.",
                            Level = "B1",
                            TextTitle = "Min garderob"
                        },
                        new
                        {
                            Id = 11,
                            Language = "Swedish",
                            LanguageText = "I helgen åkte jag och min vän Sara till Göteborg. Det är Sveriges näst största stad och ligger vid västkusten. Vi hade planerat att stanna i tre dagar för att upptäcka staden och njuta av den friska havsluften.\r\n\r\nDet som vi tycker är bäst med Göteborg är de fina parkerna och närheten till havet. Vi promenerade mycket i Slottsskogen, där det finns många djur och stora grönområden. Det var skönt att komma bort från stadens brus en stund.\r\n\r\nVi besökte också Avenyn, stadens stora huvudgata, där det finns många butiker, restauranger och kaféer. På kvällen åt vi middag på en liten fiskrestaurang vid hamnen. Maten var färsk och väldigt god.\r\n\r\nEn dag åkte vi till Liseberg, nöjesparken som är väldigt populär både bland barn och vuxna. Vi åkte karuseller, spelade på lyckohjul och åt sockervadd. Det var en rolig och lite annorlunda upplevelse.\r\n\r\nInnan vi åkte hem planerade vi redan nästa resa till Göteborg – för det finns så mycket mer att upptäcka!",
                            Level = "B1",
                            TextTitle = "Göteborg"
                        },
                        new
                        {
                            Id = 12,
                            Language = "Swedish",
                            LanguageText = "Reseagent: Hej och välkomna till Resebyrån! Hur kan jag hjälpa er idag?\r\nSara: Hej! Vi vill boka en resa till Italien i sommar. Finns det några bra erbjudanden?\r\nReseagent: Ja, vi har flera paketresor. Vill ni flyga till Rom, Milano eller kanske Neapel?\r\nErik: Vi tänkte mest på Rom. Hur länge kan vi stanna?\r\nReseagent: Det finns paket för en vecka eller två veckor. Vilket föredrar ni?\r\nSara: En vecka räcker för oss. Hur mycket kostar det per person?\r\nReseagent: Priset för en vecka i juli är 7000 kronor per person, inklusive flyg och hotell.\r\nErik: Kan vi boka ett hotell med frukost?\r\nReseagent: Självklart, alla våra paket inkluderar frukost. Vill ni ha ett rum med havsutsikt?\r\nSara: Ja, gärna! Det låter perfekt.\r\nReseagent: Då bokar jag en vecka i juli med frukost och havsutsikt. Vill ni även hyra bil?\r\nErik: Nej, vi tänker mest promenera och åka tunnelbana.\r\nReseagent: Bra val. Jag skriver ut bokningsbekräftelsen här. Tack för att ni valde oss!",
                            Level = "B1",
                            TextTitle = "Sara och Erik bokar en resa"
                        },
                        new
                        {
                            Id = 13,
                            Language = "Swedish",
                            LanguageText = "Familjen Eriksson älskar natur och de försöker besöka den botaniska trädgården varje helg när vädret är fint.\r\n\r\nSofia fascineras mest av orkidéerna. Hon tycker att deras färger och former är otroligt vackra och hon läser alltid informationen om varje art noggrant. En gång fick hon se en ovanlig orkidé som bara blommar en gång om året, och hon blev väldigt glad.\r\n\r\nJohan är mest intresserad av de stora ekarna och andra gamla träd i trädgården. Han tycker om att sitta under deras skugga och lyssna på fåglarna som sjunger i grenarna ovanför. Han brukar också fotografera träden för sitt fotoprojekt i skolan.\r\n\r\nMamma Maria älskar den japanska delen av trädgården, där det finns små dammar, stenbroar och vackra körsbärsträd. Hon njuter alltid av att promenera långsamt där och ta många bilder.\r\n\r\nPappa Anders är fascinerad av trädgårdens växthus där tropiska växter och kaktusar växer. Han kan stå länge och studera de ovanliga växterna och försöka lära sig mer om dem. Han gillar särskilt hur olika växter anpassar sig till olika klimat.\r\n\r\nEfter en lång promenad i trädgården brukar familjen sätta sig vid caféet och fika tillsammans. Det är deras favoritstund på helgen — att prata om vad de sett och planera nästa besök.",
                            Level = "B2",
                            TextTitle = "Familjen Eriksson på botaniska trädgården"
                        },
                        new
                        {
                            Id = 14,
                            Language = "Swedish",
                            LanguageText = "Svenskar älskar att fika! I Sverige har bakverken sina egna dagar då de firas. Det finns en dag för kanelbullen, för wienerbrödet och för den kanske populäraste kakan – kladdkakan! Kladdkakans dag firas den 7e november varje år. Det är en söt, kladdig och god chokladkaka som nästan alla tycker om. Prova gärna att baka en kladdkaka med detta recept:\r\n\r\nSätt ugnen på 200 °C (grader).\r\n\r\nBlanda dessa ingredienser i en bunke:\r\n\r\n- 100 gram smör\r\n- 2 stycken ägg\r\n- 2 ½ deciliter socker\r\n- 3 matskedar kakao\r\n- 2 teskedar vaniljsocker\r\n- 1 ½ deciliter vetemjöl\r\n- 1 kryddmått salt\r\n\r\nHäll smeten i en form och ställ in den i ugnen. Kakan ska gräddas i cirka 10–15 minuter. Ju kortare tid, desto kladdigare. Du kan servera kakan med vad som helst: färska bär, grädde eller kanske glass – du bestämmer!",
                            Level = "B2",
                            TextTitle = "Kladdkakans dag i Sverige"
                        },
                        new
                        {
                            Id = 15,
                            Language = "Swedish",
                            LanguageText = "Spel har utvecklats enormt under de senaste decennierna och har idag en viktig plats i många människors liv. Förutom att vara en källa till underhållning har spel också blivit en plattform för social samvaro, kreativitet och lärande.\r\n\r\nMånga uppskattar multiplayer-spel där man kan spela tillsammans med vänner eller träffa nya människor online. Genom att samarbeta eller tävla i olika spel lär man sig strategiskt tänkande, kommunikation och lagarbete. Det finns också spel som erbjuder en möjlighet att utforska fantasivärldar och berättelser på ett sätt som andra medier inte kan.\r\n\r\nE-sport har blivit en global företeelse där professionella spelare tävlar om stora prispengar och där miljontals tittare följer turneringarna via streamingtjänster. Detta har gett spel en status som en seriös sport, vilket bidrar till att förändra hur samhället ser på gaming.\r\n\r\nDet finns också en del kritik mot spel, särskilt när det gäller spelberoende och den tid många ungdomar tillbringar framför skärmarna. Det är därför viktigt att hitta en balans och att se till att spelandet inte påverkar andra delar av livet negativt.\r\n\r\nFör många är spel mer än bara en hobby – det är en passion och en gemenskap. Spelindustrin fortsätter att växa och utvecklas, och framtiden ser spännande ut med ny teknik som virtual reality och artificiell intelligens som integreras i spelupplevelsen.",
                            Level = "B2",
                            TextTitle = "Spelens värld – mer än bara underhållning"
                        },
                        new
                        {
                            Id = 16,
                            Language = "Swedish",
                            LanguageText = "Jag heter Elin och jag är åtta år gammal. Idag är jag i en nationalpark tillsammans med min familj. När jag går här bland träden känns det nästan som om jag har klivit in i en saga. Den svenska naturen är så vacker och rogivande, och jag vill berätta om allt jag ser och känner.\r\n\r\nSkogen är tät och full av höga granar och björkar. Solen strilar ner genom grenarna och gör små fläckar av ljus på marken. Jag hör fåglarna sjunga och ibland ser jag en liten ekorre som snabbt hoppar från gren till gren. Det känns som att hela skogen lever och andas.\r\n\r\nVi går längs en stig som leder fram till en glittrande sjö. Vattnet är så klart att jag kan se fiskarna simma nära ytan. Runt sjön finns mjuka mossor och blommor i alla möjliga färger. Jag plockar en liten blå blomma och sätter den i mitt hår.\r\n\r\nDet bästa med att vara här är att luften är så frisk och doftar av tall och jord. Jag känner mig lugn och glad när jag är ute i naturen. Mamma säger att vi måste ta hand om vår natur, för den är en skatt som vi alla behöver bevara.\r\n\r\nJag vill aldrig lämna den här platsen, för svensk natur är verkligen något alldeles speciellt.",
                            Level = "B2",
                            TextTitle = "Svensk natur är som en sagovärld"
                        },
                        new
                        {
                            Id = 17,
                            Language = "Polish",
                            LanguageText = "Mam na imię Kuba i mam najlepszego przyjaciela. Nazywa się Tomek. Znamy się od dzieciństwa. Mieszkamy na tej samej ulicy i chodzimy razem do szkoły.\r\n\r\nTomek ma krótkie blond włosy i niebieskie oczy. Lubi grać w piłkę nożną i słuchać muzyki. Często gramy razem na komputerze.\r\n\r\nPo szkole spotykamy się w parku albo robimy zadania domowe razem. Tomek jest miły, zabawny i zawsze mi pomaga.\r\n\r\nCieszę się, że mam takiego przyjaciela!",
                            Level = "A1",
                            TextTitle = "Mój najlepszy przyjaciel"
                        },
                        new
                        {
                            Id = 18,
                            Language = "Polish",
                            LanguageText = "Mam na imię Ola. Mam 20 lat i mieszkam w Krakowie. Każdego dnia wstaję o godzinie 7:00. Myję się, ubieram i jem śniadanie. Na śniadanie lubię jeść chleb z serem albo jajko na twardo. Zawsze piję herbatę, a czasem kawę.\r\n\r\nO 7:30 wychodzę z domu i idę na uczelnię. Mieszkam blisko, więc idę pieszo. Zajęcia zaczynają się o 8:00 i kończą się o 14:00. Studiuję psychologię i bardzo lubię moje studia.\r\n\r\nPo zajęciach wracam do domu i jem obiad. Najczęściej jem zupę i makaron albo ryż z warzywami. Potem odpoczywam, słucham muzyki lub rozmawiam z przyjaciółmi przez telefon.\r\n\r\nWieczorem często spaceruję po parku albo oglądam film. Lubię też czytać książki, zwłaszcza powieści i kryminały.\r\n\r\nKładę się spać o 22:30, bo rano muszę wcześnie wstać. Lubię mój dzień, bo jest spokojny i dobrze zorganizowany.",
                            Level = "A1",
                            TextTitle = "Mój dzień"
                        },
                        new
                        {
                            Id = 19,
                            Language = "Polish",
                            LanguageText = "W Polsce jest dużo smacznego jedzenia. Polacy lubią jeść zupy, mięso i ziemniaki. Popularne zupy to rosół, żurek i pomidorowa. Rosół to zupa z kurczakiem, marchewką i makaronem. Jest bardzo popularna w niedzielę.\r\n\r\nNa obiad Polacy często jedzą kotlet schabowy z ziemniakami i kapustą. To jest panierowane mięso, smażone na patelni. Jest bardzo pyszne!\r\n\r\nNa deser Polacy lubią pączki, sernik i szarlotkę. Pączek to słodkie ciastko z marmoladą w środku i cukrem pudrem na górze.\r\n\r\nW Polsce popularne są też pierogi. Są z różnym nadzieniem: z mięsem, z kapustą i grzybami, albo na słodko – z truskawkami lub serem.\r\n\r\nPolskie jedzenie jest ciepłe, sycące i smaczne. Bardzo je lubię!",
                            Level = "A1",
                            TextTitle = "Polskie jedzenie"
                        },
                        new
                        {
                            Id = 20,
                            Language = "Polish",
                            LanguageText = "Mam na imię Kuba i mam 10 lat. Mieszkam w Warszawie z mamą, tatą i młodszą siostrą. Chodzę do szkoły od poniedziałku do piątku. Lekcje zaczynają się o ósmej i kończą o czternastej.\r\n\r\nPo szkole jem obiad, odrabiam lekcje i potem mam czas wolny. Lubię grać w Minecrafta. To jest moja ulubiona gra! W Minecraftcie mogę budować domy, kopalnie i mosty. Czasem gram sam, a czasem z kolegami przez internet.\r\n\r\nNajbardziej lubię tryb kreatywny, bo mogę budować wszystko, co chcę. Mam też kota w grze i dużo diamentów. Granie w Minecrafta sprawia mi dużo radości!\r\n\r\nW weekendy mogę grać dłużej. To jest bardzo fajne!",
                            Level = "A1",
                            TextTitle = "Po szkole gram w Minecrafta"
                        },
                        new
                        {
                            Id = 21,
                            Language = "Polish",
                            LanguageText = "Kiedy zbliża się listopad, Ania zaczyna się bardzo cieszyć. Dlaczego? Bo w listopadzie ma urodziny! To jej ulubiony miesiąc, bo wtedy może świętować razem z rodziną i przyjaciółmi.\r\n\r\nAnia zawsze planuje swoje urodziny wcześniej. Zaczyna od robienia listy gości. Zawsze zaprasza mamę, tatę, starszego brata i młodszą kuzynkę Zosię. Nie może też zabraknąć jej najlepszej przyjaciółki Kasi, z którą chodzi do tej samej klasy.\r\n\r\nCo roku Ania wybiera temat przewodni przyjęcia. W zeszłym roku były to księżniczki, a w tym roku Ania chce, żeby wszystko było w kolorze niebieskim, bo to jej ulubiony kolor. Dekoracje, balony i nawet serwetki mają być niebieskie!\r\n\r\nNajważniejszy na przyjęciu jest oczywiście tort. Mama zawsze piecze go sama. Ania pomaga przy dekoracji – dodaje kolorową posypkę i układa świeczki. W tym roku tort będzie waniliowy z truskawkowym kremem.\r\n\r\nPo zjedzeniu tortu wszyscy grają w gry – w chowanego, kalambury i czasem nawet w karaoke! Ania zawsze dostaje dużo prezentów, ale najbardziej cieszy się z tego, że może spędzić ten dzień z bliskimi osobami.",
                            Level = "A2",
                            TextTitle = "Urodziny Ani"
                        },
                        new
                        {
                            Id = 22,
                            Language = "Polish",
                            LanguageText = "Mam na imię Michał. Mam 28 lat i mieszkam w Krakowie. To piękne miasto na południu Polski. Mieszkam tutaj od pięciu lat. Wcześniej mieszkałem w małej wiosce, ale przeprowadziłem się do miasta, żeby studiować i pracować.\r\n\r\nMam siostrę, która mieszka w Gdańsku. Rzadko się widzimy, ale często rozmawiamy przez telefon. Moi rodzice nadal mieszkają na wsi. Czasem jadę tam w weekend, żeby ich odwiedzić. Mama zawsze gotuje coś pysznego, a tata pokazuje mi, co nowego zrobił w ogrodzie.\r\n\r\nPracuję jako grafik komputerowy. Lubię swoją pracę, bo mogę być kreatywny. Pracuję z domu, więc nie muszę codziennie jeździć do biura. To bardzo wygodne. W wolnym czasie rysuję, gram w gry komputerowe i spaceruję po mieście.\r\n\r\nMam psa, który nazywa się Fado. To duży, biały pies. Chodzimy razem na spacery rano i wieczorem. Fado bardzo lubi dzieci i inne psy. Wszyscy na osiedlu go znają i lubią.\r\n\r\nLubię też podróżować. W zeszłym roku byłem w Czechach i na Słowacji. W tym roku chciałbym pojechać do Włoch. Marzę o tym, żeby zobaczyć Rzym i zjeść prawdziwą włoską pizzę!",
                            Level = "A2",
                            TextTitle = "Moje codzienne życie"
                        },
                        new
                        {
                            Id = 23,
                            Language = "Polish",
                            LanguageText = "Lubię podróżować, bo każda podróż to nowa przygoda. Mam rower, samochód i czasem korzystam z pociągu albo autobusu. Lubię też długie spacery, zwłaszcza kiedy świeci słońce. Podczas podróży można zobaczyć coś nowego i poznać ciekawych ludzi.\r\n\r\nNajczęściej podróżuję po Polsce. Byłem już w wielu miastach, takich jak Kraków, Warszawa, Gdańsk i Wrocław. Każde miasto ma coś wyjątkowego. Ale nie tylko duże miasta są interesujące. Małe miasteczka i wsie też mają swój urok. Czasem są tam piękne kościoły, stare zamki albo malownicze parki.\r\n\r\nBardzo lubię jeździć nad morze. Słuchanie szumu fal i chodzenie boso po piasku to coś wspaniałego. Moje ulubione miejsca nad morzem to Ustka i Hel. Można tam łatwo dojechać pociągiem z wielu miejsc w Polsce.\r\n\r\nLubię też góry. W Tatrach byłem kilka razy. Wędrowałem po szlakach i podziwiałem widoki. Gdy ktoś chce zobaczyć piękne krajobrazy i poczuć świeże powietrze, powinien pojechać w góry. Ale uwaga – pogoda w górach zmienia się szybko, więc trzeba być przygotowanym.\r\n\r\nNie trzeba jednak jechać daleko, żeby coś przeżyć. Czasem wystarczy wyjść z domu i pójść do pobliskiego lasu lub parku. Przyroda jest wszędzie – wystarczy tylko rozejrzeć się uważnie.\r\n\r\nA Ty? Gdzie najbardziej lubisz podróżować? Może spotkamy się kiedyś w drodze?",
                            Level = "A2",
                            TextTitle = "Podróżowanie to przygoda"
                        },
                        new
                        {
                            Id = 24,
                            Language = "Polish",
                            LanguageText = "Mam na imię Bartek. Mam 15 lat i chodzę do szkoły średniej. W wolnym czasie lubię grać na komputerze. Moją ulubioną grą jest Minecraft. Buduję tam domy, miasta, a czasem całe wyspy. Lubię też słuchać muzyki – najczęściej rocka i popu. Wieczorami często czytam książki o przygodach lub science fiction.\r\n\r\nMój młodszy brat Krzyś ma 10 lat. Bardzo lubi rysować. Ma dużo kolorowych kredek i markerów. Rysuje zwierzęta, samochody i postacie z bajek. Czasem razem gramy w gry planszowe albo budujemy coś z klocków LEGO. Krzyś nie lubi grać w gry komputerowe – mówi, że go męczą.\r\n\r\nNasza mama, pani Magda, uwielbia gotować. W weekendy próbuje nowe przepisy. Ostatnio piekła pizzę domową i robiła naleśniki z owocami. Cała rodzina je razem kolację. To dla nas ważny moment dnia.\r\n\r\nTata, pan Andrzej, często biega. Bierze udział w zawodach i trenuje kilka razy w tygodniu. W wolnym czasie lubi też czytać książki historyczne. Wie dużo o dawnych czasach i czasem opowiada nam ciekawe historie.\r\n\r\nCzasami w niedzielę wychodzimy razem na wycieczkę. Jeździmy do lasu, do zoo albo nad jezioro. Robimy zdjęcia i jemy kanapki na ławce. Lubię te chwile z rodziną. A Ty, jak spędzasz wolny czas?",
                            Level = "A2",
                            TextTitle = "Czas wolny mojej rodziny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
